-- Supabase 스키마. 대시보드 > SQL Editor에 붙여넣고 실행.
-- Supabase Auth의 auth.users를 user ID 원천으로 사용.

-- ---------- credentials: 네이버 API 자격증명 (user별) ----------
create table if not exists public.credentials (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  label          text not null,
  customer_id    text not null,
  api_key_masked text not null,
  api_key_enc    text not null,   -- AES-GCM ciphertext (base64)
  secret_key_enc text not null,
  created_at     timestamptz not null default now()
);
create index if not exists idx_credentials_user on public.credentials(user_id);

-- ---------- user_state: active_credential_id 같은 유저 상태 ----------
create table if not exists public.user_state (
  user_id              uuid primary key references auth.users(id) on delete cascade,
  active_credential_id bigint references public.credentials(id) on delete set null,
  updated_at           timestamptz not null default now()
);

-- ---------- rules: 전역 룰 저장소 (JSON) ----------
-- 기존 rules_store.json과 동일한 구조를 JSONB 한 행에 보관.
create table if not exists public.rules (
  id         int primary key default 1,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  constraint rules_singleton check (id = 1)
);

-- ---------- RLS ----------
alter table public.credentials enable row level security;
alter table public.user_state  enable row level security;
alter table public.rules       enable row level security;

-- credentials: 본인 행만
drop policy if exists "credentials own rows" on public.credentials;
create policy "credentials own rows" on public.credentials
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- user_state: 본인 행만
drop policy if exists "user_state own row" on public.user_state;
create policy "user_state own row" on public.user_state
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- rules: 로그인한 모두가 읽기/쓰기 (조직 공통 룰)
drop policy if exists "rules read all auth" on public.rules;
create policy "rules read all auth" on public.rules
  for select using (auth.role() = 'authenticated');
drop policy if exists "rules write all auth" on public.rules;
create policy "rules write all auth" on public.rules
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
